### PR TITLE
chore: Switch to Standardrb instead of stock Rubocop

### LINKED ISSUE #74: Use Standardrb over Rubocop
[Standardrb](https://github.com/standardrb/standard) is an opinionated formatter and linter built on top of Rubocop, drastically reducing the configuration needed to be maintained. It's widely adopted in the community, and I think it's a compelling alternative to using stock Rubocop and associated extensions, which we're currently doing.

### PR DESCRIPTION
**Pull request by maxveldink**
## This PR

Switches from stock Rubocop to Standardrb. 

- Removes `rubocop` and adds `standard` and `standard-performance` has dependencies
- Remove Rubocop configuration in favor of Standard configuration
- Updates Rake and CI to use Standard
- Applies Standard recommendations

### Related Issues

Fixes #74

### CODE REVIEW

**Comment by josecolella** [comment]
@maxveldink: 

thought:
--
- Is there a benefit to moving to standardrb over rubocop?

**Comment by maxveldink** [comment]
The benefit I find with Standard is that it minimizes the number of Rubocop configuration decisions that need to be made. The ruleset they've settled on is fairly binary, and it's typically simple formatting while still getting the nice linting and performance warnings from Rubocop. Whenever I try to use stock Rubocop, I'm constantly fighting with the ruleset, or running into rules that don't apply to the specific project.

Besides that, it's a minor process change that is easy to adopt earlier in a project, which is why I proposed it now.

**Review by beeme1mr — APPROVED** [review]
I'm fine with this change but I'll defer to the Ruby maintainers for final approval.

**Review by josecolella — APPROVED** [review]

**Comment by maxveldink** [comment]
🙏🏻

**Pull request merged**
