### PR TITLE
feat!: Add `EvaluationContext` helpers and context merging to flag evaluation

### LINKED ISSUE #111: Setting a context for a client?
I'm unsure on how to set a context for a client, e.g., a default context that all evaluations will use. Is there documentation on this/is this something that's possible? 

I.e., something like this:

```ruby
client.evaluation_context = EXAMPLE_CONTEXT

flag_details = client.fetch_boolean_details(flag_key: "ExampleBooleanFlag", default_value: false)
```

Additionally, passing a context to flag evaluations in general is not really well documented, probably something that would be handy to add to the README.

### PR DESCRIPTION
**Pull request by maxveldink**
## This PR
This is largely a port of this behavior from the [Sorbet implementation](https://github.com/maxveldink/openfeature-sdk-sorbet/blob/main/lib/open_feature/evaluation_context_builder.rb) my company originally started with.

- Updated arguments to be `evaluation_context` across the board more explicitly
- Ensures that we allow for API, Client and invocation contexts to be passed
- Refactor `EvaluationContext` to have a cleaner initializer signature and add `==` and `merge` convenience methods
- Use `EvaluationContextBuilder` during flag evaluation to reconcile all contexts
- Removes test that is now covered in specification tests

### Related Issues
Closes #111 

### Follow-up Tasks
- Still need to implement transaction propagation for evaluation contexts
- More tests for client flag evaluation

### CODE REVIEW

**Review by beeme1mr — APPROVED** [review]
Please make sure to update the readme examples.

**Comment by maxveldink** [comment]
@beeme1mr Good callout, added some examples

**Review by beeme1mr — APPROVED** [review]
Do we need to worry about thread safety?

**Comment by maxveldink** [comment]
I don't think we're overly concerned with thread safety here. We haven't run into any issues with a similar implementation yet. Happy to take a look at any bugs that pop up around that though!

**Pull request merged**
