### PR TITLE
test: Clarify Requirement 1.1.1

### PR DESCRIPTION
**Pull request by maxveldink**
## This PR
I've begun work on the Flag Evaluation API section of the OpenFeature specification. I decided to go from top to bottom (similar to the current unit tests) and ensure there hasn't been any spec drift from the original work done here. 

Additionally, I propose maintaining a separate `specification` set of RSpec tests that correspond 1 to 1 with the specification as written. Currently, we're doing this in line with the unit tests. Still, I foresee situations where we'll want to drive out behavior in unit tests that don't necessarily correspond to a requirement (or when multiple unit tests could satisfy a requirement). Freeing the unit tests of the responsibility of tracking spec compliance seems beneficial.

Finally, I _think_ 1.1.1 can be demonstrated

- Adds a new `specification` folder for tracking specification compliance
- Adds comment where we satisfy the requirement in the source code

### Follow-up Tasks
I am working on each requirement in the Flag Evaluation API from spec version 0.7.0 and will have PRs this week. 

### How to test
There is no change to current behavior; a passing RSpec suite should be sufficient.

### CODE REVIEW

**Review by josecolella — DISMISSED** [review]

**Comment by maxveldink** [comment]
@mschoenlaub Good call on using conventional commits; I don't in my day job and really should do that everywhere 😂 I've got another PR to switch to Standard (#76 ) that hopefully will be committed to before this, so I'll defer fixing the Rubocop warning until I can check with that linter.

**Comment by maxveldink** [comment]
@josecolella @technicalpickles Any chance we can get some 👀 on this 🙏🏻

**Review by josecolella — DISMISSED** [review]
Nit: looks good, I would say that the comment is unnecessary since the inclusion of the Singleton module should already enforce the requirement

**Review by beeme1mr — APPROVED** [review]

**Comment by maxveldink** [comment]
@josecolella Agreed, removed 🙏🏻

**Review by technicalpickles — APPROVED** [review]

**Pull request merged**
